// Package api exposes a REST interface for frontend clients.
//
// Routes:
//
//	GET /api/formats?url=<url>  – fetch available formats for a video URL
//	GET /api/jobs                – list all jobs
//	GET /api/jobs/{file_id}       – get a single job by its file_id
//
// Download jobs are no longer submitted over HTTP: they arrive on the Kafka
// job-requests topic and are handled by HandleJobMessage.
package api

import (
	"context"
	"encoding/json"
	"log/slog"
	"net/http"
	"os"
	"strings"
	"time"

	"downloader/internal/downloader"
	"downloader/internal/storage"
)

// Server handles REST requests for the frontend and job requests from Kafka.
type Server struct {
	db        *storage.DB
	outDir    string
	publishFn func(ctx context.Context, fileID string) error // publishes job completion to Kafka
	log       *slog.Logger
}

// New creates a Server. publishFn is called with the job's file_id on every
// completion (ready or failed); consumers fetch the outcome via GET /api/jobs/{file_id}.
func New(
	db *storage.DB,
	outDir string,
	publishFn func(ctx context.Context, fileID string) error,
	log *slog.Logger,
) *Server {
	return &Server{
		db:        db,
		outDir:    outDir,
		publishFn: publishFn,
		log:       log,
	}
}

// RegisterRoutes mounts all API handlers on mux.
func (s *Server) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/api/formats", s.handleFormats)
	mux.HandleFunc("/api/jobs", s.listJobs)
	mux.HandleFunc("/api/jobs/", s.handleJob)
}

// ── GET /api/formats?url=<url> ────────────────────────────────────────────────

// formatsResponse offers a standardized quality ladder rather than yt-dlp's
// raw per-video format list (which varies wildly by site). VideoHeights is
// capped to what the source actually has; AudioFormats is a fixed set since
// every target is a transcode. See downloader.AvailableHeights.
type formatsResponse struct {
	Title        string   `json:"title"`
	Duration     float64  `json:"duration"` // seconds; 0 when the source doesn't report it
	VideoHeights []int    `json:"video_heights"`
	AudioFormats []string `json:"audio_formats"`
}

func (s *Server) handleFormats(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	url := r.URL.Query().Get("url")
	if url == "" {
		http.Error(w, "url query parameter is required", http.StatusBadRequest)
		return
	}

	info, err := downloader.FetchVideoInfo(r.Context(), url)
	if err != nil {
		s.log.Warn("api: fetch formats failed", "url", url, "err", err)
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}

	writeJSON(w, http.StatusOK, formatsResponse{
		Title:        info.Title,
		Duration:     info.Duration,
		VideoHeights: downloader.AvailableHeights(info.Formats),
		AudioFormats: downloader.StandardAudioFormats(),
	})
}

// ── job requests (Kafka) / GET /api/jobs ─────────────────────────────────────

// jobRequest is the JSON value read from the job-requests Kafka topic.
// FileID is generated by the requester so it can correlate the eventual
// completion notification (which carries only file_id) back to this job.
//
// Kind selects which of the fields below apply:
//   - "video": Height (one of the standard tiers from GET /api/formats) and
//     WithAudio (mux the best available audio track, or leave video-only).
//   - "audio": AudioFormat, one of the standard targets from GET /api/formats
//     ("mp3" is the default when empty).
type jobRequest struct {
	FileID   string  `json:"file_id"`
	URL      string  `json:"url"`
	Title    string  `json:"title,omitempty"`
	Duration float64 `json:"duration,omitempty"` // seconds, from GET /api/formats; 0 = unknown
	Kind     string  `json:"kind"`

	Height    int  `json:"height,omitempty"`
	WithAudio bool `json:"with_audio,omitempty"`

	AudioFormat string `json:"audio_format,omitempty"`
}

type jobResponse struct {
	ID           int64  `json:"id"`
	FileID       string `json:"file_id"`
	URL          string `json:"url"`
	Title        string `json:"title"`
	QualityLabel string `json:"quality_label"`
	Status       string `json:"status"`
	Error        string `json:"error,omitempty"`
	CreatedAt    string `json:"created_at"`
	DownloadURL  string `json:"download_url,omitempty"`
}

// HandleJobMessage processes a single job request received from Kafka: it
// persists the job, then runs the download and publishes completion.
// Called from the Kafka consumer loop, so it never writes an HTTP response.
func (s *Server) HandleJobMessage(ctx context.Context, value []byte) {
	var req jobRequest
	if err := json.Unmarshal(value, &req); err != nil {
		s.log.Warn("api: bad job message", "err", err)
		return
	}
	if req.FileID == "" || req.URL == "" {
		s.log.Warn("api: job message missing file_id or url")
		return
	}

	var format downloader.Format
	var outputFormat string
	switch req.Kind {
	case "audio":
		format = downloader.BuildAudioFormat(req.AudioFormat)
	default:
		format = downloader.BuildVideoFormat(req.Height, req.WithAudio)
		if req.WithAudio {
			// Two separately-selected streams need an explicit container to remux into.
			outputFormat = "mp4"
		}
	}

	if err := os.MkdirAll(s.outDir, 0o755); err != nil {
		s.log.Error("api: create out dir", "err", err)
		return
	}

	// Persist the record before the (potentially slow, e.g. for playlist
	// URLs) title lookup below, so GET /api/jobs/{file_id} finds it right
	// away instead of racing the caller's poll loop with a 404.
	titleKnown := req.Title != ""
	if !titleKnown {
		req.Title = req.URL // placeholder until the lookup below resolves
	}

	record := &storage.Download{
		FileID:       req.FileID,
		URL:          req.URL,
		Title:        req.Title,
		FormatArg:    format.Arg,
		QualityLabel: format.Label,
	}
	if err := s.db.Save(ctx, record); err != nil {
		s.log.Error("api: save record", "err", err)
		return
	}
	s.log.Info("api: job accepted", "job_id", record.ID, "file_id", record.FileID)

	if !titleKnown {
		info, err := downloader.FetchVideoInfo(ctx, req.URL)
		if err != nil {
			s.log.Warn("api: fetch title failed", "url", req.URL, "err", err)
		} else {
			req.Title = info.Title
			record.Title = info.Title
			if err := s.db.UpdateTitle(ctx, record.ID, info.Title); err != nil {
				s.log.Error("api: update title", "job_id", record.ID, "err", err)
			}
		}
	}

	// Run the download in the background so the Kafka consumer loop can keep
	// reading subsequent job requests without waiting for this one to finish.
	// Bounded by a duration-based timeout so a hung yt-dlp process eventually
	// gets killed instead of leaving the job "pending" forever.
	timeout := downloader.EstimateTimeout(time.Duration(req.Duration * float64(time.Second)))
	dlCtx, cancel := context.WithTimeout(context.Background(), timeout)
	go func() {
		defer cancel()
		s.runDownload(dlCtx, record, downloader.Request{
			FileID:       req.FileID,
			URL:          req.URL,
			Title:        req.Title,
			Format:       format,
			OutDir:       s.outDir,
			OutputFormat: outputFormat,
		})
	}()
}

func (s *Server) listJobs(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	records, err := s.db.List(r.Context())
	if err != nil {
		s.log.Error("api: list jobs", "err", err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}
	resp := make([]jobResponse, len(records))
	for i, dl := range records {
		resp[i] = toJobResponse(dl)
	}
	writeJSON(w, http.StatusOK, resp)
}

// ── GET /api/jobs/{file_id} ───────────────────────────────────────────────────

func (s *Server) handleJob(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	fileID := strings.TrimPrefix(r.URL.Path, "/api/jobs/")
	if fileID == "" {
		http.Error(w, "missing file id", http.StatusBadRequest)
		return
	}

	dl, err := s.db.GetByFileID(r.Context(), fileID)
	if err != nil {
		s.log.Error("api: get job", "file_id", fileID, "err", err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}
	if dl == nil {
		http.Error(w, "job not found", http.StatusNotFound)
		return
	}
	writeJSON(w, http.StatusOK, toJobResponse(*dl))
}

// ── helpers ───────────────────────────────────────────────────────────────────

// runDownload executes the download in a goroutine, updates the DB, and
// publishes the job ID to Kafka so consumers can fetch the outcome.
func (s *Server) runDownload(ctx context.Context, record *storage.Download, req downloader.Request) {
	result, err := downloader.Download(ctx, req)

	if err != nil {
		s.log.Error("api: download failed", "job_id", record.ID, "err", err)
		if dbErr := s.db.UpdateError(ctx, record.ID, err.Error()); dbErr != nil {
			s.log.Error("api: update error status", "job_id", record.ID, "err", dbErr)
		}
	} else {
		if dbErr := s.db.UpdateOutputPath(ctx, record.ID, result.FilePath); dbErr != nil {
			s.log.Error("api: update output path", "job_id", record.ID, "err", dbErr)
		}
		s.log.Info("api: download done", "job_id", record.ID, "file_id", record.FileID)
	}

	if err := s.publishFn(ctx, record.FileID); err != nil {
		s.log.Warn("api: publish completed failed", "job_id", record.ID, "file_id", record.FileID, "err", err)
	}
}

func toJobResponse(dl storage.Download) jobResponse {
	r := jobResponse{
		ID:           dl.ID,
		FileID:       dl.FileID,
		URL:          dl.URL,
		Title:        dl.Title,
		QualityLabel: dl.QualityLabel,
		Status:       dl.Status,
		Error:        dl.ErrorMsg,
		CreatedAt:    dl.CreatedAt.UTC().Format("2006-01-02T15:04:05Z"),
	}
	if dl.Status == "ready" {
		r.DownloadURL = "/files/" + dl.FileID
	}
	return r
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(v)
}
